apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-ns-test
  namespace: argocd
spec:
  description: Syncs ArgoCD Applications and Projects from https://github.com/BennWigh/argocd-envs
  destinations:
  - namespace: 'argocd'
    server: https://kubernetes.default.svc
  - namespace: 'my-ns-test'
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: 'argoproj.io'
    kind: 'AppProject'
  - group: 'argoproj.io'
    kind: 'Application'
  sourceRepos:
  - https://github.com/BennWigh/argocd-envs
  - https://github.com/BennWigh/benn-test-helm