apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-projects
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: argocd-resources
  source:
    repoURL: https://dev.azure.com/okamba/Infrastruktur/_git/argocd-resources
    targetRevision: HEAD
    path: projects

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: false
      selfHeal: false